# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sauron_pb2 as sauron__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sauron_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SauronMeshStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareThreatIntel = channel.unary_unary(
                '/sauron.SauronMesh/ShareThreatIntel',
                request_serializer=sauron__pb2.ThreatBatch.SerializeToString,
                response_deserializer=sauron__pb2.Ack.FromString,
                _registered_method=True)
        self.SyncPolicy = channel.unary_unary(
                '/sauron.SauronMesh/SyncPolicy',
                request_serializer=sauron__pb2.PolicyUpdate.SerializeToString,
                response_deserializer=sauron__pb2.Ack.FromString,
                _registered_method=True)
        self.ShareTelemetry = channel.unary_unary(
                '/sauron.SauronMesh/ShareTelemetry',
                request_serializer=sauron__pb2.TelemetrySnapshot.SerializeToString,
                response_deserializer=sauron__pb2.Ack.FromString,
                _registered_method=True)
        self.SyncModel = channel.unary_unary(
                '/sauron.SauronMesh/SyncModel',
                request_serializer=sauron__pb2.ModelDelta.SerializeToString,
                response_deserializer=sauron__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sauron.SauronMesh/Heartbeat',
                request_serializer=sauron__pb2.Ping.SerializeToString,
                response_deserializer=sauron__pb2.Pong.FromString,
                _registered_method=True)
        self.Gossip = channel.unary_unary(
                '/sauron.SauronMesh/Gossip',
                request_serializer=sauron__pb2.GossipDigest.SerializeToString,
                response_deserializer=sauron__pb2.GossipDigest.FromString,
                _registered_method=True)
        self.StreamIntel = channel.stream_stream(
                '/sauron.SauronMesh/StreamIntel',
                request_serializer=sauron__pb2.ThreatEvent.SerializeToString,
                response_deserializer=sauron__pb2.ThreatEvent.FromString,
                _registered_method=True)


class SauronMeshServicer:
    """Missing associated documentation comment in .proto file."""

    def ShareThreatIntel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIntel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SauronMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareThreatIntel': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareThreatIntel,
                    request_deserializer=sauron__pb2.ThreatBatch.FromString,
                    response_serializer=sauron__pb2.Ack.SerializeToString,
            ),
            'SyncPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPolicy,
                    request_deserializer=sauron__pb2.PolicyUpdate.FromString,
                    response_serializer=sauron__pb2.Ack.SerializeToString,
            ),
            'ShareTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareTelemetry,
                    request_deserializer=sauron__pb2.TelemetrySnapshot.FromString,
                    response_serializer=sauron__pb2.Ack.SerializeToString,
            ),
            'SyncModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncModel,
                    request_deserializer=sauron__pb2.ModelDelta.FromString,
                    response_serializer=sauron__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=sauron__pb2.Ping.FromString,
                    response_serializer=sauron__pb2.Pong.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=sauron__pb2.GossipDigest.FromString,
                    response_serializer=sauron__pb2.GossipDigest.SerializeToString,
            ),
            'StreamIntel': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamIntel,
                    request_deserializer=sauron__pb2.ThreatEvent.FromString,
                    response_serializer=sauron__pb2.ThreatEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sauron.SauronMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sauron.SauronMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SauronMesh:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShareThreatIntel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/ShareThreatIntel',
            sauron__pb2.ThreatBatch.SerializeToString,
            sauron__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/SyncPolicy',
            sauron__pb2.PolicyUpdate.SerializeToString,
            sauron__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/ShareTelemetry',
            sauron__pb2.TelemetrySnapshot.SerializeToString,
            sauron__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/SyncModel',
            sauron__pb2.ModelDelta.SerializeToString,
            sauron__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/Heartbeat',
            sauron__pb2.Ping.SerializeToString,
            sauron__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sauron.SauronMesh/Gossip',
            sauron__pb2.GossipDigest.SerializeToString,
            sauron__pb2.GossipDigest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIntel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sauron.SauronMesh/StreamIntel',
            sauron__pb2.ThreatEvent.SerializeToString,
            sauron__pb2.ThreatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
